### PR TITLE
Updates to unit tests for db

### PR DESCRIPTION
**Pull request by eacharles**

### CODE REVIEW

**Review by fritzm — COMMENTED** [review]
A few questions:

* Are you quite sure about needing to making `run_bash_job` sync?  It is the textbook case of making a potentially unboundedly lengthy OS call, and that call interface itself supports async usage.  If we make this sync, calling it indirectly under any API call should be prohibited, otherwise we can hang the web service for all other usage/clients.

* Lots of `#pragma: no cover` added here.  Most seem like exception cases.  Are these deemed either too difficult or not worth test coverage?  Do we want to pretend they are covered?

**Comment by eacharles** [comment]
Yes, that was why I originally had it as async.   Colin requested that the equivalent htcondor and slurm launching scripts be sync, so I changed this one for consistency.   Up to you guys to sort it out.

I don't think that writing complicated test cases for every exception is a sensible use of an of our time.  I covered the once that were easy to cover and pragma'd the others.

**Comment by fritzm** [comment]
Thanks, Eric.  I'd like to understand @ctslater's POV here.  In your opinion, is this something we should have in asap to unblock folks (and rework later if needed), or can it wait for me to chat w/ Colin about it tomorrow?

**Comment by eacharles** [comment]
It can wait a day.-eOn Oct 2, 2024, at 10:42 PM, Fritz Mueller ***@***.***> wrote:﻿
Thanks, Eric.  I'd like to understand @ctslater's POV here.  In your opinion, is this something we should have in asap to unblock folks (and rework later if needed), or can it wait for me to chat w/ Colin about it tomorrow?

**Review by fritzm — APPROVED** [review]

**Pull request merged**
