### PR TITLE
DM-41577: squash and merge `eac-dev` to `main`

### PR DESCRIPTION
**Pull request by fritzm**

### CODE REVIEW

**Comment by eacharles** [comment]
This is the best code I've ever seen.   Surely it sprung fully formed, sun generis, from the blood of dying gods.   

We must merge this immediately to bring an end to the dark ages and cast off the shackles of our oppression.

**Review by eacharles — APPROVED** [review]
This extraordinary code should be merged immediately to bring light unto the masses that they may rejoice.

**Comment by eacharles** [comment]
Cool that each linter gots its own vision, looking forward to meta linter!!

**Comment by eacharles** [comment]
Looks like the tickets/DM-41377 branch is being pushed around..

**Comment by fritzm** [comment]
Okay, I think I'm done fiddling with the PR now.

* Had a go with ruff ALL, and it found a lot of interesting stuff, some of which I think is actually substantial and which we'll want to discuss/ticket/fix after the merge.

* Let ruff do a bunch of trivial auto-fixes, and hand implemented a few more of its suggestions which I thought would be non-controversial.  These are on one commit and probably aren't review-worthy, other than having a peek here and there if you wish to see the sorts of things that were changed.

* Fixed the warning re. deprecated FastAPI lifetime event handlers by just upgrading to the latest new hotness there.

* Found a way to address the annoying lint with name shadowing in pytest fixtures, so was able to remove `# pylint: disable`s there.

* There is something really unsavory still happening with session management in the test suite, which you can see it whinging about when you `make test`...  I stared hard at it for a while, but didn't find an immediate fix.  We'll probably want to return to work on this soon also

**Pull request merged**
